<a href="https://colab.research.google.com/github/skdixodnr/my_study/blob/main/20230502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def swap_value(x, y):
  temp = x
  x = y
  y = temp

def swap_offset(offset_x,offset_y):
  temp = a[offset_x]
  a[offset_x] = a[offset_y]
  a[offset_y] = temp

def swap_reference(list, offset_x,offset_y):
  temp = list[offset_x]
  list[offset_x] = list[offset_y]
  list[offset_y] = temp

a =[1,2,3,4,5]
swap_value(a[1],a[2])
print(a)
swap_offset(1,2)
print(a)
swap_reference(a,1,2)
print(a)

[1, 2, 3, 4, 5]
[1, 3, 2, 4, 5]
[1, 2, 3, 4, 5]


- 이 함수는 두개의 숫자를 input으로 받으면 작은 수로 큰 수를 나눈 몫과 나머지를 반환하는 함수이다.
- 반환 값은 튜플로 되어 있으며 몫,나머지 순으로 되어 있다.
- 단,0으로 나누는 것을 불가하기 때문에 두 수 중에 작은 수가 0이라면 화면에"0은 사용할 수 없습니다."라고 출력하고 종료되어야한다.

In [ ]:
def div(n1, n2):
  t1 = n2//n1, n2%n1
  t2 = n1//n2, n1%n2
  if n1<n2:
    print(t1[0:2])
  elif n1 == 0 or n2 == 0:
    print("0은 사용할 수 없습니다.")
  else:
    print(t2[0:2])

div(-1,-5)


(0, -1)


In [ ]:
# 답안
def div3(a,b):
  if a<b:
    big=b
    small=a
  elif b<=a:
    big=a
    small=b
  else:
    print("정수가 아닙니다.")
  if small==0:
    print("0은 사용할 수 없습니다.")
  elif abs(big)<0 or abs(small)<0:
    print("정수를 입력해주세요.")
  else:
    q= big//small
    r= big%small
    return (q,r)
div(9,2)

(4, 1)


- 어떠한 string을 받으면 일정한 단위로 끊어서 화면에 출력하는 함수를 짜보자.
- 끊는 단위는 따로 정하지 않으면 2로 설정해보자.
- 힌트 : input을 string과 unit = 2로 받고,while을 사용하고, 길이는 len 함수를 사용하도록 하자.

In [ ]:
def func(string, unit=2):
  i=0
  while i<len(string):
    print(string[i:i+unit])
    i +=unit
func("테스트를 위한 문장입니다.")

In [ ]:
def test(*args):
  print(args)
test(1,2,3,4,5,6,7,8,9,10)
test([1,2],3)
test([1,2])

- add_all 함수를 짜봅시다

In [ ]:
def add_all(*args):
  result = 0
  for i in args:
    result += i
  return result
result1 = add_all(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(result1)

55


In [ ]:
def add_all(*inputs):
  s=0
  for i in range(len(inputs)):
    s +=inputs[i]
  return s
result1 = add_all(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(result1)

55


In [ ]:
def add_all(*inputs):
  return sum(inputs)

add_all(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

55

In [ ]:
def add_all3(*args):
    s=0
    for i in args:
      for j in i:
        s +=j
      return s

add_all3([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

55

In [ ]:
import numpy as np
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [ ]:
np.arange(3,50,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [ ]:
np.linspace(0,1,6) # 0 부터 1 까지 6번 쪼갠다

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

- 배열 결합 함수
  - hstack,concatenate(axis=0)
  - 두 배열을 왼쪽에서 오른쪽으로 붙이기.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- vstack(vertical),concatenate(axis=1)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a,b),axis=1) # 1D는 vector는 안됨.

In [ ]:
c = np.array([[0,1,2],[3,4,5]])
d = np.array([[6,7,8],[9,10,11]])

np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

- 두 배열을 위 아래로 붙이기.

In [ ]:
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.column_stack([a,b])


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
import random
import numpy as np

In [ ]:
random.random()  # 0<리턴값<=1

0.307229960365891

In [ ]:
data = [1,2,3,4,5,6,7]

np.random.choice(data,3)

array([2, 5, 3])

In [ ]:
data = ["apple", "banana", "grape", "orange"]

random.choice(data)

'banana'

- seed
  - 난수 초기값부여 -> 재현 가능성(Reporducibility)

In [ ]:
np.random.seed(42)

In [ ]:
np.random.rand(100)

- 로또 번호 생성기를 만드세요.

In [ ]:
import numpy as np
import random
def make_lotto(count):
  for i in range(count):
    lotto_num = [] # 로또 번호가 담길 리스트형 변수
    for j in range(6): # 6번 반복
      lotto_num = np.random.choice(range(1,46),6,replace=False) # replace=False -> 중복추출
      lotto_num.sort()
    print('{}.로또번호:{}'.format(i+1,lotto_num))


In [ ]:
count = int(input('로또 번호를 몇개 몇개 생성할까요?'))
make_lotto(count)

로또 번호를 몇개 몇개 생성할까요?16
1.로또번호:[ 8 10 21 29 39 45]
2.로또번호:[ 1  5 17 21 24 39]
3.로또번호:[ 4 29 30 37 43 44]
4.로또번호:[ 8 25 32 38 42 44]
5.로또번호:[ 2  4  5 28 35 37]
6.로또번호:[13 28 29 31 35 42]
7.로또번호:[ 1  2  5 17 31 39]
8.로또번호:[ 8 12 19 21 33 39]
9.로또번호:[ 3  5  6 33 34 44]
10.로또번호:[ 7 12 23 27 33 42]
11.로또번호:[ 5 10 11 14 30 45]
12.로또번호:[ 4 25 29 35 39 41]
13.로또번호:[14 33 35 36 42 45]
14.로또번호:[ 1  4 16 22 25 32]
15.로또번호:[ 1 16 18 29 31 32]
16.로또번호:[ 2  7 12 13 22 28]


In [ ]:
def add_all(*args):
  